language: python
os:
- linux
services:
- docker
python:
- '3.6'
install:
- pip install .
- pip install pytest
script: pytest
deploy:
  provider: pypi
  user: magland
  on:
    tags: true
  password:
    secure: O04xpeTYkzQ+QKDvQn17dV95AwGu8pRzbo81ZWRtG3dOtafF5sH3j+bC9brWsWiUWUdreFQ00jtYDQtwNRccaTlbuWA21pKYggwpwZcZ2vgAlmHxvOGLkZH15J3nSkBj/lEEG8L3NgMf11GSGXTXdLgD3/iiRxIZC27zuzO0KBCs0WlGZATk0OdSe//1oT6vrswN+CLC6dcgkr05wiMEQ9IiINxlt3y7hFfQeis4nLiN6vVL3h0bzzNnMWac89iQ3dBQ72xh9+p+wJz2KvCYKmtY0jwFugJ6XXR0TEDT0jCxIZHKEVE+6ueRJqyAOJtUVZImRwH7XPfYROVuVCJYs6LTvSsVrCMhkDY20alvvj77cIhHRzQifVbBniGO6a9hGxoQXzVzK0Oah6++nQOwJuzrqDLSS/QkmP2IJ9TU3ZwgqXiSHUnnzlacR5zywRKH7PBj56C0Z8+08iYUde6gtBiQUzcySzHF65EutAJQGPMgyDCCPPBNerUhDCVOTmt7Zg3bC7edGtGDjUNJFBiFtaED6fKsd5MHJ+5RTULd1yftiv/wZpaG5fAX5o2G627s1dw0kW9s2aH3g5+AMlwhyoW6/WoSpTwXrjwefOp8H/oUwB0bn5Ujq/UajQUaK4X0rHUGUxGlEiw2yIL2iWTluzeJxWjcHMlDQKVVbTURf2g=
